// Reclaim Phase 4 W1 — IRS-style Substantiation Record generator.
//
// Produces the document the brief §7 calls "the product's most valuable and
// defensible output." Two formats:
//   - IRS PDF (primary): cover page + per-expense detail page with embedded
//     receipt image and the user's confirmation timestamp (the moat).
//   - CSV: one row per expense, machine-readable.
//
// Design notes:
//   - Generation runs client-side. The PDF is downloaded directly to the
//     user; no PHI-laden artifact is persisted server-side. The DB tracks
//     that a record was generated and the user can regenerate any time.
//   - All field values are SNAPSHOTS (substantiation_record_items) — so
//     even if the underlying invoice is edited or deleted later, the record
//     continues to cite the values that existed at confirmation time.
//   - The defensibility statement on the cover page is the brand voice for
//     auditor-facing communication. Update with care.

import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { logError } from "@/utils/errorHandler";

export interface SubstantiationExpenseInput {
  invoiceId: string;
  vendor: string;
  date: string; // YYYY-MM-DD
  patientName: string | null;
  category: string | null;
  amount: number;
  ruleName: string | null;
  ruleSectionRef: string | null;
  confirmedAt: string; // ISO timestamp
  receiptPaths: string[]; // storage paths under the receipts bucket
}

export interface SubstantiationHeader {
  recordNumber: string;
  taxYear: number;
  generatedAt: string;
  userName: string;
  totalAmount: number;
  expenseCount: number;
}

const DEFENSIBILITY_STATEMENT =
  "This record was generated by Reclaim. Each expense listed was personally confirmed eligible by the account holder on the confirmation timestamp shown. These contemporaneous timestamps serve as the account holder's substantiation under IRC §213(d) and HSA distribution record-keeping requirements (IRS Pub 969).";

const IMAGE_MIME_RX = /^image\/(png|jpeg|jpg|webp)$/i;

// ── Helpers ──────────────────────────────────────────────────────────────

function fmtDateLong(iso: string): string {
  const d = new Date(iso.length === 10 ? iso + "T00:00:00" : iso);
  return d.toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function fmtTimestamp(iso: string): string {
  const d = new Date(iso);
  return (
    d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    }) +
    " at " +
    d.toLocaleTimeString(undefined, {
      hour: "2-digit",
      minute: "2-digit",
      timeZoneName: "short",
    })
  );
}

function fmtMoney(n: number): string {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

async function fetchReceiptAsDataUrl(
  path: string,
): Promise<{ dataUrl: string; mime: string } | null> {
  try {
    const { data, error } = await supabase.storage
      .from("receipts")
      .createSignedUrl(path, 600);
    if (error || !data?.signedUrl) return null;
    const resp = await fetch(data.signedUrl);
    if (!resp.ok) return null;
    const blob = await resp.blob();
    const mime = blob.type || "application/octet-stream";
    if (!IMAGE_MIME_RX.test(mime)) {
      // Non-image (PDF, etc.) — we don't embed; the cover note explains.
      return null;
    }
    const dataUrl: string = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    return { dataUrl, mime };
  } catch (err) {
    logError("substantiationRecord: fetchReceiptAsDataUrl", err);
    return null;
  }
}

function imageFormatForJsPdf(mime: string): "PNG" | "JPEG" | "WEBP" {
  const m = mime.toLowerCase();
  if (m.includes("png")) return "PNG";
  if (m.includes("webp")) return "WEBP";
  return "JPEG";
}

// ── Cover page ───────────────────────────────────────────────────────────

function drawCover(doc: jsPDF, header: SubstantiationHeader) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 56; // ~3/4 inch

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Substantiation Record", margin, 96);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text("Generated by Reclaim", margin, 116);
  doc.setTextColor(0);

  // Identification block
  let y = 168;
  const left = margin;
  const labelW = 150;
  const lineGap = 22;

  const writeRow = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(110);
    doc.text(label, left, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text(value, left + labelW, y);
    y += lineGap;
  };

  writeRow("Record number", header.recordNumber);
  writeRow("Tax year", String(header.taxYear));
  writeRow("Generated", fmtTimestamp(header.generatedAt));
  writeRow("Account holder", header.userName);
  writeRow(
    "Expenses included",
    `${header.expenseCount} ${header.expenseCount === 1 ? "expense" : "expenses"}`,
  );
  writeRow("Total amount", fmtMoney(header.totalAmount));

  // Defensibility footer
  y = doc.internal.pageSize.getHeight() - 140;
  doc.setDrawColor(220);
  doc.line(margin, y, pageW - margin, y);
  y += 24;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  const wrapped = doc.splitTextToSize(
    DEFENSIBILITY_STATEMENT,
    pageW - margin * 2,
  );
  doc.text(wrapped, margin, y);
}

// ── Per-expense page ─────────────────────────────────────────────────────

async function drawExpensePage(
  doc: jsPDF,
  index: number,
  total: number,
  expense: SubstantiationExpenseInput,
) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;

  // Page header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`Expense ${index} of ${total}`, margin, 64);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text(expense.vendor, pageW - margin, 64, { align: "right" });
  doc.setTextColor(0);

  // Metadata block
  let y = 100;
  const labelW = 200;
  const lineGap = 18;

  const row = (label: string, value: string, mono = false) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(label, margin, y);
    doc.setFont(mono ? "courier" : "helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0);
    const wrapped = doc.splitTextToSize(value, pageW - margin - labelW);
    doc.text(wrapped, margin + labelW, y);
    y += Math.max(lineGap, wrapped.length * 13);
  };

  row("Patient", expense.patientName ?? "Self");
  row("Date of service", fmtDateLong(expense.date));
  row("Provider / Vendor", expense.vendor);
  row("Category", expense.category ?? "(uncategorized)");
  row("Amount", fmtMoney(expense.amount));
  row(
    "IRS Pub 502 basis",
    expense.ruleName
      ? `${expense.ruleName}${expense.ruleSectionRef ? ` — ${expense.ruleSectionRef}` : ""}`
      : "(unclassified — review required)",
  );
  row(
    "Reclaim confirmation timestamp",
    fmtTimestamp(expense.confirmedAt),
    true,
  );

  // Receipt
  y += 12;
  doc.setDrawColor(220);
  doc.line(margin, y, pageW - margin, y);
  y += 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text("RECEIPT", margin, y);
  doc.setTextColor(0);
  y += 14;

  if (expense.receiptPaths.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(140);
    doc.text("No receipt attached.", margin, y);
    doc.setTextColor(0);
    return;
  }

  // Embed up to 2 receipt images per expense to keep file size reasonable;
  // extras get a note. PDF receipts can't be embedded as raster — we note
  // them as "PDF attached separately" since the user has the original in
  // their account.
  const MAX_EMBED = 2;
  let embedded = 0;
  for (const path of expense.receiptPaths) {
    if (embedded >= MAX_EMBED) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(140);
      doc.text(
        `${expense.receiptPaths.length - embedded} additional receipt(s) on file.`,
        margin,
        y,
      );
      doc.setTextColor(0);
      break;
    }
    const fetched = await fetchReceiptAsDataUrl(path);
    if (!fetched) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(140);
      doc.text("Original receipt on file (non-image format).", margin, y);
      doc.setTextColor(0);
      y += 14;
      continue;
    }
    const maxW = pageW - margin * 2;
    const remainingH = pageH - margin - y;
    const targetW = Math.min(maxW, 360);
    const targetH = Math.min(remainingH - 24, 420);
    try {
      doc.addImage(
        fetched.dataUrl,
        imageFormatForJsPdf(fetched.mime),
        margin,
        y,
        targetW,
        targetH,
        undefined,
        "FAST",
      );
      y += targetH + 16;
      embedded++;
    } catch (err) {
      logError("substantiationRecord: addImage", err);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(140);
      doc.text("Receipt image could not be embedded.", margin, y);
      doc.setTextColor(0);
      y += 14;
    }
  }
}

// ── Public PDF builder ───────────────────────────────────────────────────

export async function generateSubstantiationRecordPDF(
  header: SubstantiationHeader,
  expenses: SubstantiationExpenseInput[],
): Promise<Blob> {
  const doc = new jsPDF({
    unit: "pt",
    format: "letter",
    orientation: "portrait",
  });

  drawCover(doc, header);

  for (let i = 0; i < expenses.length; i++) {
    doc.addPage();
    // eslint-disable-next-line no-await-in-loop -- sequential by design (preserves page order)
    await drawExpensePage(doc, i + 1, expenses.length, expenses[i]);
  }

  return doc.output("blob");
}

// ── CSV builder ──────────────────────────────────────────────────────────

function csvEscape(value: string): string {
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function generateSubstantiationRecordCSV(
  header: SubstantiationHeader,
  expenses: SubstantiationExpenseInput[],
): string {
  const rows: string[] = [];
  rows.push(
    `# Reclaim Substantiation Record ${header.recordNumber} — Tax Year ${header.taxYear}`,
  );
  rows.push(`# Generated ${fmtTimestamp(header.generatedAt)}`);
  rows.push(
    `# Account holder: ${header.userName} — ${header.expenseCount} expenses, ${fmtMoney(header.totalAmount)} total`,
  );
  rows.push(
    [
      "date_of_service",
      "patient",
      "vendor",
      "category",
      "amount_usd",
      "irs_pub_502_basis",
      "irs_pub_502_section",
      "reclaim_confirmation_timestamp",
      "receipt_count",
    ]
      .map(csvEscape)
      .join(","),
  );
  for (const e of expenses) {
    rows.push(
      [
        e.date,
        e.patientName ?? "Self",
        e.vendor,
        e.category ?? "",
        e.amount.toFixed(2),
        e.ruleName ?? "",
        e.ruleSectionRef ?? "",
        e.confirmedAt,
        String(e.receiptPaths.length),
      ]
        .map((v) => csvEscape(String(v)))
        .join(","),
    );
  }
  return rows.join("\n");
}

// ── Browser download helper ──────────────────────────────────────────────

export function downloadBlob(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5_000);
}
